version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
        - ./src:/work

  web:
    image: nginx:1.18-alpine
    ports:
        - 10080:80
    volumes:
        - ./src:/work
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
        - db-store:/var/lib/mysql
    environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD}
        - TZ=Asia/Tokyo
    ports:
        - 33060:3306

volumes:
    db-store: